packages:
- '.'
- location: './taffybar'
  extra-dep: true
- location:
    git: https://github.com/willdonnelly/dyre
    commit: 11412752b483135e0c151ab90be17b217f837c4b
  extra-dep: true
extra-deps:
  # - Cabal-2.0.1.1
  - rate-limit-1.1.1
  - time-units-1.0.0
  - gtk-traymanager-0.1.6
  - xmonad-contrib-0.13
  - xml-helpers-1.0.0
  - xml-1.3.14
  - gtk-0.14.7
  - gio-0.13.4.0
  - libxml-sax-0.7.5
  - HStringTemplate-0.8.6
  - colors-0.3.0.2
resolver: lts-10.1
allow-newer: true
