#!/bin/sh -eu

################################################################################
# Edit this file and then rename it to ~/.xmonad/build

################################################################################
# The directory holding your source code and stack.yaml file:
SRC_DIR=$HOME/.xmonad

################################################################################
# The name of the executable produced by stack.  This comes from the
# executable section of your Cabal file.
EXE_NAME=xmonadfn

################################################################################
# This script will be given a single argument, the path to the
# executable it should produce.
output_file=$1; shift
pwd

################################################################################
cd $SRC_DIR
stack build
rm $output_file
cp -u `stack path --local-install-root`/bin/$EXE_NAME $output_file
